SELECT LAST_NAME, SALARY, EMAIL, HIRE_DATE, JOB_ID, SALARY
FROM employees;

desc employees;

SELECT LAST_NAME, SALARY, EMAIL, HIRE_DATE, JOB_ID, SALARY+5000
FROM employees;

SELECT LAST_NAME, COMMISSION_PCT
FROM employees;

SELECT LAST_NAME, COMMISSION_PCT, SALARY*COMMISSION_PCT AS "SALARY wITH COMI", SALARY
FROM employees;

