--CLASS_WORK
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 4000 AND 8000
ORDER BY SALARY;


SELECT*
FROM EMPLOYEES
WHERE HIRE_DATE > '01-JAN-2003'
ORDER BY HIRE_DATE DESC;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 
OR DEPARTMENT_ID = 80
ORDER BY DEPARTMENT_ID, LAST_NAME;
--CLASS_WORK_END

SELECT CONCAT('MY FIRST NAME IS ', CONCAT(FIRST_NAME, CONCAT(' AND MY LAST NAME IS ', LAST_NAME)))
FROM EMPLOYEES;

SELECT LAST_NAME, SUBSTR(LAST_NAME, 1, 3), CONCAT(SUBSTR(LAST_NAME, 1, 4), '_US'),
UPPER(CONCAT(SUBSTR(LAST_NAME, 1, 5), ':_Us'))
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60;

SELECT ROUND(45.926, 2)
FROM DUAL;

SELECT TRUNC(45.926, 2)
FROM DUAL;

SELECT CEIL(45.000000000000000000000000000000000000006)
FROM DUAL;

SELECT FLOOR(45.92)
FROM DUAL;

SELECT MOD(45.926, 46)
FROM DUAL;

SELECT SYSDATE
FROM DUAL;

SELECT HIRE_DATE, ROUND((SYSDATE-HIRE_DATE)/7,2) AS WEAK, ROUND((SYSDATE-HIRE_DATE)/365, 2) AS YEAR
FROM EMPLOYEES;

SELECT CURRENT_TIMESTAMP
FROM DUAL;

SELECT HIRE_DATE, MONTHS_BETWEEN(CURRENT_TIMESTAMP, HIRE_DATE)
FROM EMPLOYEES;



