SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 4000 AND 8000
ORDER BY SALARY;


SELECT*
FROM EMPLOYEES
WHERE HIRE_DATE > '01-JAN-2003'
ORDER BY HIRE_DATE DESC;

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50 
OR DEPARTMENT_ID = 80
ORDER BY DEPARTMENT_ID, LAST_NAME;