select current_timestamp
from dual;

select sysdate
from dual;


SELECT to_char(SYSDATE, 'DAY-DD-MON-YYYY MI DDSPTH , HH12:MI:SS AM-- SS, SSSSS FMDDSPTH')
FROM DUAL;

SELECT LAST_NAME, 
TO_CHAR(HIRE_DATE, 'DDSPTH MON/YYYY') AS HIREDATE
FROM EMPLOYEES;

SELECT COMMISSION_PCT, NVL(COMMISSION_PCT, 0)
FROM EMPLOYEES;


SELECT COMMISSION_PCT, 
NVL(COMMISSION_PCT, 0), 
NVL2(COMMISSION_PCT, SALARY+(SALARY*COMMISSION_PCT), SALARY) AS "TOTAL SALARY"
FROM EMPLOYEES;

SELECT COMMISSION_PCT, 
NVL(COMMISSION_PCT, 0), 
NVL2(COMMISSION_PCT, SALARY+(SALARY*COMMISSION_PCT), SALARY) AS "TOTAL SALARY", 
FIRST_NAME LENGTH(FIRST_NAME), 
NULLIF()
FROM EMPLOYEES;

SELECT LAST_NAME, JOB_ID, SALARY, CASE JOB_ID
WHEN 'IT_PROG' THEN 1.10*SALARY
WHEN 'ST_CLERK' THEN 1.15*SALARY
WHEN 'SA_REP' THEN 1.20*SALARY
else salary end "rev_salary"
from employees;

SELECT LAST_NAME, JOB_ID, SALARY,
DECODE(JOB_ID, 'IT_PROG', 1.10*SALARY,
'ST_CLERK', 1.15*SALARY,
'SA_REP', 1.20*SALARY,
SALARY)
"rev_salary"
from employees;


SELECT LAST_NAME, JOB_ID, SALARY, CASE
WHEN SALARY<5000 THEN 'LOW'
WHEN SALARY<10000 THEN 'MEDIUM'
WHEN SALARY<20000 THEN 'HIGH'
else 'EXCELLENT' end "rev_salary"
from employees;



--6TH-CHAPTER

SELECT JOB_ID, COUNT(JOB_ID),
MAX(SALARY), AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT
MAX(SALARY), AVG(SALARY), department_id, COUNT(department_id)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, SUM(SALARY) PAYROLL
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%REP%'
GROUP BY JOB_ID
HAVING SUM(SALARY)> 13000
ORDER BY SUM(SALARY);